Script started on 2020-10-06 20:15:45-06:00
]0;stuart.johnstone@csa2:~/Documents/cs355stuart.johnstone@csa2:~/Documents/cs355$ exitstopquit./a.outgcc assign2b.s[1P.sa.s
]0;stuart.johnstone@csa2:~/Documents/cs355stuart.johnstone@csa2:~/Documents/cs355$ gcc assign2a.sexit[Kstopquit./a.out

please input a number between 5 and 20 
5
76931
The SUM of the list is 26
LARGEST frequency 34
SMALLEST frequency 3
]0;stuart.johnstone@csa2:~/Documents/cs355stuart.johnstone@csa2:~/Documents/cs355$ exit
exit

Script done on 2020-10-06 20:15:58-06:00
