Script started on 2020-11-16 12:32:08-07:00
]0;stuart.johnstone@csa2:~/Documents/cs355/Assignment_4stuart.johnstone@csa2:~/Documents/cs355/Assignment_4$ bash b.sh
GNU gdb (GDB) Fedora 8.1.1-4.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./a.out...(no debugging symbols found)...done.
(gdb) r 1 1
Starting program: /home/ugb/stuart.johnstone/Documents/cs355/Assignment_4/a.out 1 1
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

Missing separate debuginfos, use: dnf debuginfo-install glibc-2.27-38.fc28.aarch64
warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Need exactly two arguements inbetween 4 and 16
[Inferior 1 (process 9953) exited with code 057]
(gdb) r 17 178[K
Starting program: /home/ugb/stuart.johnstone/Documents/cs355/Assignment_4/a.out 17 17
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Need exactly two arguements inbetween 4 and 16
[Inferior 1 (process 9958) exited with code 057]
(gdb) r 1 17
Starting program: /home/ugb/stuart.johnstone/Documents/cs355/Assignment_4/a.out 1 17
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Need exactly two arguements inbetween 4 and 16
[Inferior 1 (process 9961) exited with code 057]
(gdb) r 17 1
Starting program: /home/ugb/stuart.johnstone/Documents/cs355/Assignment_4/a.out 17 1
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Need exactly two arguements inbetween 4 and 16
[Inferior 1 (process 9965) exited with code 057]
(gdb) r 4 4
Starting program: /home/ugb/stuart.johnstone/Documents/cs355/Assignment_4/a.out 4 4
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

7 6 9 3 Frequency: 36 Index 2 
1 15 10 12 Frequency: 39 Index 1 
9 13 10 11 Frequency: 30 Index 1 
2 11 3 6 Frequency: 50 Index 1 
[Inferior 1 (process 9969) exited with code 027]
(gdb) r 16 16
Starting program: /home/ugb/stuart.johnstone/Documents/cs355/Assignment_4/a.out 16 16
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

7 6 9 3 1 15 10 12 9 13 10 11 2 11 3 6 Frequency: 11 Index 5 
12 2 4 8 11 8 7 13 6 10 14 3 3 15 9 10 Frequency: 11 Index 13 
6 2 13 7 1 8 3 10 5 13 5 7 8 9 14 4 Frequency: 12 Index 14 
11 2 13 6 11 4 4 1 14 2 4 1 1 13 12 7 Frequency: 13 Index 8 
0 9 14 1 1 1 12 7 14 1 14 7 10 12 11 6 Frequency: 11 Index 10 
15 8 12 10 12 0 11 11 2 15 12 4 12 8 11 12 Frequency: 9 Index 9 
2 10 14 3 11 10 10 10 11 9 1 6 5 12 12 4 Frequency: 10 Index 2 
5 8 14 1 9 9 12 11 8 9 15 5 1 11 1 3 Frequency: 12 Index 10 
5 15 7 0 9 1 10 5 10 11 11 0 8 7 4 13 Frequency: 12 Index 1 
15 3 14 8 12 11 4 5 4 3 10 5 14 11 9 3 Frequency: 11 Index 0 
11 0 4 4 1 14 9 12 10 4 12 2 11 0 15 11 Frequency: 12 Index 14 
3 13 3 0 8 7 5 12 11 15 2 9 10 11 13 5 Frequency: 11 Index 9 
11 1 10 12 15 3 8 9 8 4 11 3 5 10 14 8 Frequency: 11 Index 4 
8 2 8 0 9 13 13 4 12 15 14 7 10 11 12 5 Frequency: 10 Index 9 
12 6 1 11 10 10 5 2 14 0 5 3 11 4 12 3 Frequency: 12 Index 8 
6 4 3 15 2 0 4 14 15 2 5 9 13 2 14 9 Frequency: 12 Index 8 
[Inferior 1 (process 9973) exited with code 027]
(gdb) q
]0;stuart.johnstone@csa2:~/Documents/cs355/Assignment_4stuart.johnstone@csa2:~/Documents/cs355/Assignment_4$ q[Kexit
exit

Script done on 2020-11-16 12:32:46-07:00
